version: '3.4'

services:
  proceso-nocturno:
    container_name: proceso-nocturno
    build: .
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ENDPOINT=${ENDPOINT}
      - PORT=${PORT}
      - USER=${USER}
      - PASSWD=${PASSWD}
      - DBNAME=${DBNAME}
      - ACCESS_KEY_AWS=${ACCESS_KEY_AWS}
      - SECRET_KEY_AWS=${SECRET_KEY_AWS}
      - ACCESS_KEY_ESTAFETA=${ACCESS_KEY_ESTAFETA}
      - SECRET_KEY_ESTAFETA=${SECRET_KEY_ESTAFETA}
      - SESSION_TOKEN_ESTAFETA=${SESSION_TOKEN_ESTAFETA}
      - SFTP_PALACIO_KEY=${SFTP_PALACIO_KEY}
    ports:
      - 8000:8000

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: proceso-nocturno --interval 600 --cleanup
