version: '3.4'

services:
  proceso-nocturno:
    image: 100430482908.dkr.ecr.us-east-1.amazonaws.com/proceso-nocturno:latest
    container_name: proceso-nocturno
    build: .
    env_file:
      - .env
    volumes:
      - ./nocturno:/app/
    ports:
      - 8000:8000

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: proceso-nocturno --interval 600 --cleanup
