# Generated by Django 4.1.1 on 2022-12-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_alter_fechaactual_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_ekbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_ekko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_ekpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_fret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_knop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_lfa1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_mara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_mean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_mseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_t001l_erp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_t161t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_tlog_x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_tlogf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_trans_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_trans_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_trans_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('trans_colum', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_trans_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('trans_colum', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_trans_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('trans_colum', models.IntegerField()),
                ('trans_colum_2', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_tstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_val_vb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_vbrk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_vbrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_process', models.DateTimeField()),
                ('storeday_colum', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('second_store', models.FloatField()),
            ],
        ),
    ]
