# Generated by Django 4.1.1 on 2023-01-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_tabla_ekbe_tabla_ekko_tabla_ekpo_tabla_fret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_ekbe',
            name='storeday_colum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tabla_ekko',
            name='storeday_colum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tabla_ekpo',
            name='storeday_colum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tabla_fret',
            name='storeday_colum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tabla_mara',
            name='storeday_colum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tabla_mseg',
            name='storeday_colum',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tabla_tlog_x',
            name='storeday_colum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tabla_tlogf',
            name='storeday_colum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tabla_val_vb',
            name='storeday_colum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tabla_vbrp',
            name='storeday_colum',
            field=models.IntegerField(),
        ),
    ]
