# Generated by Django 4.1.1 on 2023-01-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0005_alter_tabla_ekbe_storeday_colum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_val_vb',
            name='count',
            field=models.FloatField(),
        ),
    ]
