# Generated by Django 4.1.1 on 2023-01-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0006_alter_tabla_val_vb_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanderaSaveJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('day_process', models.DateTimeField()),
                ('status_bandera', models.FloatField()),
            ],
        ),
    ]
