# Generated by Django 4.1.1 on 2023-01-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0007_banderasavejobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banderasavejobs',
            name='status_bandera',
            field=models.CharField(max_length=30),
        ),
    ]
